/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#ff385c',
        'primary-active': '#e00b41',
        'primary-disabled': '#ffd1da',
        'primary-error-text': '#c13515',
        'primary-error-text-hover': '#b32505',
        luxe: '#460479',
        plus: '#92174d',
        ink: '#222222',
        body: '#3f3f3f',
        muted: '#6a6a6a',
        'muted-soft': '#929292',
        hairline: '#dddddd',
        'hairline-soft': '#ebebeb',
        'border-strong': '#c1c1c1',
        canvas: '#ffffff',
        'surface-soft': '#f7f7f7',
        'surface-card': '#ffffff',
        'surface-strong': '#f2f2f2',
        'on-primary': '#ffffff',
        'on-dark': '#ffffff',
        'legal-link': '#428bff',
        'star-rating': '#222222',
        scrim: '#000000',
      },
      fontFamily: {
        sans: ['Airbnb Cereal VF', 'Circular', '-apple-system', 'system-ui', 'Roboto', 'Helvetica Neue', 'sans-serif'],
      },
      borderRadius: {
        xs: '4px',
        sm: '8px',
        md: '14px',
        lg: '20px',
        xl: '32px',
        full: '9999px',
      },
      spacing: {
        xxs: '2px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        base: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '64px',
      },
    },
  },
  plugins: [],
}
